### PR TITLE
refactor: use highlight.js

### PR DESCRIPTION
**Pull request by baszalmstra**
Adds highlight.js as the syntax highlighter. This ensures that we use the same library for the documentation as for the website. 

Note that a copy of the build folder of highlight.js is added so that we can override the use of this package in package.json.

### CODE REVIEW

**Comment by Wodann** [comment]
Is there a reason why you didn't add highlight.js as a submodule?

**Comment by baszalmstra** [comment]
Yes, because the repo only contains the source code, whereas this includes
a build version. All of this should no longer be necessary once we
stabilize our syntax and can merge Mun upstream to hightlightjs.

**Comment by Wodann** [comment]
Can't the build directory be placed outside of the source directory?

**Comment by baszalmstra** [comment]
Superseded by #38

**Pull request closed without merging**
